std_msgs/Header header

# Turn Signal enumeration
TurnSignal turn_signal

# High beams
HighBeam high_beam_headlights

# Front Windshield Wipers enumeration
WiperFront wiper

# Buttons
bool cruise_resume_button
bool cruise_cancel_button
bool cruise_accel_button
bool cruise_decel_button
bool cruise_on_off_button
bool adaptive_cruise_on_off_button
bool adaptive_cruise_increase_distance_button
bool adaptive_cruise_decrease_distance_button
bool steer_wheel_button_a
bool steer_wheel_button_b
bool steer_wheel_button_c
bool steer_wheel_button_d
bool steer_wheel_button_e

# Door status
bool driver_door_ajar
bool passenger_door_ajar
bool rear_left_door_ajar
bool rear_right_door_ajar
bool liftgate_ajar
bool any_seatbelt_unbuckled
bool airbag_deployed
bool door_or_hood_ajar
