std_msgs/Header header

Ignition ignition_state 
HornState horn_state 

# Lights
TurnSignal turn_signal_state 
bool turn_signal_sync
HighBeamState high_beam_state 
LowBeam low_beam_state 

# Wipers
WiperFront front_wiper_state 
WiperRear rear_wiper_state 

# Doors
DoorState right_rear_door_state 
DoorState left_rear_door_state 
DoorState liftgate_door_state 
DoorLock door_lock_state

uint8 rolling_counter
